apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointme-prod
  namespace: argocd
  annotations:
    # Format: notifications.argoproj.io/subscribe.<trigger>.<service>: ""
    notifications.argoproj.io/subscribe.on-deployed.github: ""
spec:
  project: default
  source:
    repoURL: 'https://github.com/fhswf/appointme'
    targetRevision: HEAD
    path: k8s/apps/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: appointme-prod
  syncPolicy:
    automated: {}
