apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appointme-dev
resources:
  - ../../base
images:
  - name: ghcr.io/fhswf/appointme/backend
    newTag: 1.43.0-rc.1
patches:
  - path: configmap-patch.yaml
