apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointme-frontend-dev
  namespace: argocd
  labels:
    component: frontend
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
    link.argocd.argoproj.io/external-link: "https://appointme.gawron.cloud/"
spec:
  project: default
  source:
    repoURL: 'https://github.com/fhswf/appointme'
    targetRevision: HEAD
    path: client/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: appointme-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
