apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointme-infra-dev
  namespace: argocd
  labels:
    component: infra
spec:
  project: default
  source:
    repoURL: 'https://github.com/fhswf/appointme'
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: appointme-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
