apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointme-api-prod
  namespace: argocd
  labels:
    component: api
    app.kubernetes.io/part-of: appointme
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
    link.argocd.argoproj.io/external-link: "https://appointme.fh-swf.cloud/api"
spec:
  project: default
  source:
    repoURL: 'https://github.com/fhswf/appointme'
    targetRevision: HEAD
    path: backend/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: appointme-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
