apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointme-infra-prod
  namespace: argocd
  labels:
    component: infra
    app.kubernetes.io/part-of: appointme
spec:
  project: default
  source:
    repoURL: 'https://github.com/fhswf/appointme'
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: appointme-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
