apiVersion: v1
kind: ConfigMap
metadata:
  name: appointme
data:
  API_URL: "https://appointme.fh-swf.cloud/api/v1"
  BASE_URL: "https://appointme.fh-swf.cloud"
  REACT_APP_API_URL: "https://appointme.fh-swf.cloud/api/v1"
  REACT_APP_URL: "https://appointme.fh-swf.cloud"
  SMTP_HOST: "smtp.fh-swf.de"
  SMTP_PORT: "465"
  SMTP_SECURE: "true"
