apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appointme-prod
resources:
  - ../../base
images:
  - name: ghcr.io/fhswf/appointme/backend
    newTag: 1.43.0
patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: appointme
