apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointme-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fhswf/appointme'
    targetRevision: HEAD
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: appointme-staging
  syncPolicy:
    automated: {}
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: argocd-secret
    jsonPointers:
    - /data
  orphanedResources:
    warn: true
    ignore:
      - kind: Secret
        name: "argocd-secret"
