apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/cgawron/bin/kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: appointme
  name: appointme
  namespace: appointme
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appointme
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /home/cgawron/bin/kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/traefik: 'true'
        io.kompose.service: appointme
    spec:
      initContainers:
        - name: migrations
          image: ghcr.io/fhswf/appointme/backend:latest
          command:
            - node
            - backend/build/scripts/run-migrations.js
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URI
                  name: appointme
      containers:
        - env:


            - name: NODE_ENV
              value: production

          volumeMounts:
            - name: config
              mountPath: "/etc/config"
              readOnly: true
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
          image: ghcr.io/fhswf/appointme/backend:latest
          name: appointme
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 20
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: config
          configMap:
            name: appointme
        - name: secrets
          secret:
            secretName: appointme-secret
            defaultMode: 0400
status: {}
