apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../backend/k8s/overlays/dev
  - ../../../client/k8s/overlays/dev
  - ../../../mcp-server/k8s/overlays/dev
  - argocd.yaml
namespace: appointme-dev
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: appointme-ingress
